version: '3'

services:
  my-fastapi-app:
    image: msrajawat298/chat_with_mayank
    restart: always
    ports:
      - "80:8000"  # Only accessible from localhost
    command: /bin/sh -c "git restore app.py && git pull && python app.py && tail -f /dev/null"
